### ISSUE TITLE
Strange response to query

### ISSUE THREAD

**Issue by dscape** [marklogic-community/Corona#1]
Request

```
  http://localhost:4380/json/query?q=fox
```

Response

```
{"meta":{"start":1,"end":1,"total":2},"results":[{"uri":"/foo/another_snow","content":{"foo":"to find something you could eat fox"}}]}
```

Question: If I didn't state start and end shouldnt this return both results that match?

**Comment by ryangrimm** [comment]
Yes, we could have these types of requests return all of the matches, but what about the case when there is 1,000,000 matches?  That's not a response that anyone wants.  So I in going along with the idea that the defaults should all be fast and efficient, simply returning the first result seemed like a prudent thing to do.

**Comment by dscape** [comment]
What about returning 10? That seems reasonable.

Also any advice on how to fix the test?

Nuno

On Tue, Sep 6, 2011 at 4:32 PM, isubiker
reply@reply.github.com
wrote:

**Comment by ryangrimm** [comment]
We could return the first 10.  But I went with just one to be consistant with how the kvquery operates.  Open to changes.

As far as fixing the test, I'm not sure what the test is so I can't offer any suggestions :).

**Comment by eedeebee** [comment]
1 - feels like a minor issue.
2 - the current default is rarely if ever what you want, right?
3 - first 10 seems reasonable to me

**Comment by ryangrimm** [comment]
Start still exits but end has been changed to length.  Length defaults to 10 for /search and 1 for /kvquery.
