### ISSUE TITLE
RFE: Include elapsed-time in results

### ISSUE THREAD

**Issue by hunterhacker** [marklogic-community/Corona#10]
Seems like it may help people to have an elapsed time in the responses.  For example: It lets you compare different queries reliably without concern for network latency overhead.  It lets you record historic performance to a log.

At minimum this would be good on search results, but anything where there's a structured response it seems useful.  And cheap on the MarkLogic side.

**Comment by eedeebee** [comment]
I like.  Wonder if this is something modal/orthogonal you could turn on/off globally.

**Comment by hunterhacker** [comment]
Why would someone turn it off?

**Comment by eedeebee** [comment]
Maybe it's always on.  All I could come up with for turning it off is
- leaky details I don't want my users to know
- every bit counts in bwidth especially if response bodies are small.

**Comment by hunterhacker** [comment]
I wonder how often will people send the raw response to their users?

Every bit counts, but only if it puts you over the next 1500 byte MTU limit.  :)

**Comment by eedeebee** [comment]
I suspect some folks will write direct browser<->Corona apps on occasion.  It's not good if the bulk of the response is eaten by data I don't care about:  <foo elapsed-time="...."/>

E

**Comment by hunterhacker** [comment]
If they do that, they have bigger issues than the browser seeing the elapsed time. A malicious browser could delete all their data.

We may want to think about how best to enable safe browser<->Corona communication.

**Comment by ryangrimm** [comment]
Included as an executionTime key or element, depending on the response type.
