### ISSUE TITLE
RFE: Filtered vs unfiltered search option

### ISSUE THREAD

**Issue by hunterhacker** [marklogic-community/Corona#16]
We should give developers the ability to do filtered or unfiltered searches.  The default should probably be unfiltered, but when you need filtering you really need it.  We just need to be able to explain it to non-experts.  Here's a stab at that:

"The default search behavior is 'unfiltered' where results are returned based solely on index resolution.  The optional 'filter' flag indicates each result should additionally be examined to verify it matches the query before being returned.  If your query includes a constraint that won't reliably resolve from indexes, this will ensure you get accurate results.  Beware that the query execution may take longer to process, possibly a very long time if most results returned from indexes aren't truly matches."

**Comment by eedeebee** [comment]
Suspect you know, but you have to also explain how and why a query couldn't
be accurately resolved from indexes.

How do I know when I might care about this?

-Eric

On Fri, Sep 30, 2011 at 11:37 PM, Jason Hunter <
reply@reply.github.com>wrote:

> We should give developers the ability to do filtered or unfiltered
> searches.  The default should probably be unfiltered, but when you need
> filtering you really need it.  We just need to be able to explain it to
> non-experts.  Here's a stab at that:
> 
> "The default search behavior is 'unfiltered' where results are returned
> based solely on index resolution.  The optional 'filter' flag indicates each
> result should additionally be examined to verify it matches the query before
> being returned.  If your query includes a constraint that won't reliably
> resolve from indexes, this will ensure you get accurate results.  Beware
> that the query execution may take longer to process, possibly a very long
> time if most results returned from indexes aren't truly matches."
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/marklogic/Corona/issues/16

## 

Eric Bloch
  616 Virginia Avenue, San Mateo, CA 94402
  Email: eric.bloch@gmail.com
  Web page: http://www.virginia-avenue.com/
  Phone: 650-458-8929

**Comment by ryangrimm** [comment]
Added into the query string as a GET parameter.  Turns out the custom queries supported it all along!  The things I forget that I implemented.
