### ISSUE TITLE
Doc insert with no string provided should not return 200

### ISSUE THREAD

**Issue by collwhit** [marklogic-community/Corona#19]
The following request returns 200, with no indication that the document insert has failed (and it does fail).

xdmp:http-put("http://localhost:8004/xml/store",
     <options xmlns="xdmp:http">
       <data>
           {xdmp:quote("<a>mydoc</a>")}
       </data>
       <authentication method="digest">
         <username>user</username>
         <password>pass</password>
       </authentication>
     </options>)

Seems like it ought to return 400.

**Comment by ryangrimm** [comment]
You are correct, this was a bug and it should return a 400.  Just committed a fix.
