### ISSUE TITLE
Weight on geo is currently ignored, should prob not expose

### ISSUE THREAD

**Issue by hunterhacker** [marklogic-community/Corona#43]
http://developer.marklogic.com/pubs/5.0/apidocs/cts-query.html#cts:element-geospatial-query says

"$weight (optional): A weight for this query. The default is 1.0. This option is currently ignored; geospatial queries do not contribute to the score."

So I'd remove that feature from Corona until such time as we can implement it.  It's OK with me if you keep the code the same, but remove it from the docs.

**Comment by ryangrimm** [comment]
Remved from the docs, code still exists.
