### ISSUE TITLE
setup throws an error

### ISSUE THREAD

**Issue by crichey** [marklogic-community/Corona#48]
When I hit the setup.xqy at http://localhost:8010/config/setup.xqy I get the following error. The framework otherwise seems to be functioning fine, indicating that I have the correct configuration for the url rewriter.
{"error":{"status":404,"code":"corona:ENDPOINT-NOT-FOUND","message":"Invalid endpoint. Check path and parameters for errors."}}

**Comment by eedeebee** [comment]
I wonder if any of the config should be established using the 5.0 config mechanism.

**Comment by crichey** [comment]
Maybeinteresting idea. I think only users are being created though so

## probably overkill.

Clark Richey
clark@clarkrichey.com

On 11/19/11 2:31 PM, "Eric Bloch"
<reply+i-2289465-bb7174e9d6e2d85cc1fb431938d7b7af6879125a-214112@reply.gith
ub.com> wrote:

**Comment by ryangrimm** [comment]
Oops, this error was introduced when I put in the new error handler and rewriter last week.  I just pushed some changes that should fix things up.  As a side note, the setup script now lives at /config/setup (dropping the .xqy).

**Comment by ryangrimm** [comment]
Regarding the use of the 5.0 config goodies, I'm guessing that you're referring to the REST interface that has been created.  I'd be open to using it as the admin function calls are kind of painful.  However, that leaves the 4.1 and 4.2 folks out in the insecure cold.  So for the time being I think we should stick with using the admin API.

**Comment by crichey** [comment]
Actually it would be the package management but I think it is overkill in

## this case. I think the existing approach is much better.

Clark Richey
clark@clarkrichey.com

On 11/19/11 3:19 PM, "Ryan Grimm"
<reply+i-2289465-bb7174e9d6e2d85cc1fb431938d7b7af6879125a-214112@reply.gith
ub.com> wrote:

**Comment by crichey** [comment]
Works now

**Comment by ryangrimm** [comment]
Excellent. Thanks for finding and reporting. I'll cook up a test for the setup page to catch further issues.
