### ISSUE TITLE
RFE: Applying stylesheets to the Corona ResultSet

### ISSUE THREAD

**Issue by sastafford** [marklogic-community/Corona#55]
Could we have the stylesheet referenced by the 'applyTransform' parameter being applied to the result set instead of the individual documents.  I have a use case where I may want to return a CSV result set instead of an Corona XML result set.  If I apply a stylsheet/xquery to the result set I can still transform the individual documents but now I can transform the result set to any type of format I want.

**Comment by eedeebee** [comment]
What do you want to happen when the result set is large and not returned all in one api call?

**Comment by sastafford** [comment]
I got around this issue by creating a new endpoint based on the present search.xqy endpoint.  After getting my result set back from store:outputMultipleDocuments, I apply a stylesheet to the result set into my desired format.  A better solution recommended by Jason Hunter.
