### ISSUE TITLE
More detailed logging

### ISSUE THREAD

**Issue by crichey** [marklogic-community/Corona#56]
Please log POST parameters. Troubleshooting is much harder when I can't see what POST parameters the server is seeing.

**Comment by ryangrimm** [comment]
This might be best handled in the REST library (ml-rest-lib).  I'll do some checking to see if logging POST vars can be turned on or if that would need to be implemented.

**Comment by eedeebee** [comment]
I wonder if this is more of an issue when you're writing a language client (like ActiveDocument) as opposed to an app directly on the REST apis.

**Comment by crichey** [comment]
I think that whenever you are dynamically generating the parameters you
want the logging. I know what I think I'm sending URL encoded and I can
put in some debugging to verify but I would be much more comfortable if
the server told me what IT thinks I'm sending as that is what really

## matters.

Clark Richey
clark@clarkrichey.com

On 11/28/11 5:35 PM, "Eric Bloch"
<reply+i-2374220-eddc723ba2671c364573facdee397a9c6936ac17-214112@reply.gith
ub.com> wrote:

**Comment by hunterhacker** [comment]
We have a lot of language clients to write, so this will be good to help write them.

**Comment by crichey** [comment]
It would also be good to see the HTTP verb being reported for the request. yes, it is in the access log but having in consolidated would be good.

**Comment by eedeebee** [comment]
We just saw a case where this would have helped someone (Tom Hubschman) trying to make a PUT from java.

**Comment by ryangrimm** [comment]
Actually, in this case, the response contained all the info that would be required to debug ({"error":{"status":400,"code":"corona:INVALID-REQUEST","message":"Missing document body"}}), only the response body wasn't being printed out for failing requests.

That said, as a result I actually am about to commit a couple changes so every error is always logged.
