### ISSUE TITLE
Reusable saved queries

### ISSUE THREAD

**Issue by hunterhacker** [marklogic-community/Corona#59]
The reverse query implementation will require persisted queries, and if we have that we should enable those queries to be executed forward as well as reverse.  See discussion in Issue #47.

**Comment by ryangrimm** [comment]
Implemented and tested, not yet documented.

**Comment by ryangrimm** [comment]
Added documentation.

**Comment by hunterhacker** [comment]
Still need to make the query reusable, at least in the structured syntax.

**Comment by hunterhacker** [comment]
Any reason not to close this now?

**Comment by ryangrimm** [comment]
Yes, no documentation or tests for the namedQuery constructor at the moment.

**Comment by ryangrimm** [comment]
Docs and tests now exist for use in structured queries as well as string queries.  Also have tests and docs for named query prefix management.
