### ISSUE TITLE
Allow transform on input

### ISSUE THREAD

**Issue by hunterhacker** [marklogic-community/Corona#61]
Colleen had the idea to enable transforms on input.

We agree this isn't as important as transforms on output.  That's because on output you can save yourself a big data transfer, while on input you've already made the big data transfer.  But it does seem like a nice to have.

Implementation-wise you could specify an applyTransform parameter on insertion.  Easy.

It might also be possible to do applyPipeline if someone setup an Info Studio pipeline separately.  Have to think and research about that one.

**Comment by eedeebee** [comment]
I asked Ryan for this one a while ago as well.  I think it's valuable.  Why store (and index) stuff you don't care about?  Also enables someone to "fixup" data on the way in or add some additional information.

**Comment by ryangrimm** [comment]
When inserting or updating content an applyTransform parameter can now be supplied.
