### ISSUE TITLE
Tutorial: be Windows friendly

### ISSUE THREAD

**Issue by hunterhacker** [marklogic-community/Corona#64]
Introduce curl tool, say how to get it on Windows or point at a Windows alternative.

**Comment by eedeebee** [comment]
I added the following to page 3 of the current tutorial.  Could do more if need be.

If you haven't seen the <code>curl</code> tool before, it's a popular command line http client, that is ideal for playing with REST apis. If you don't have a copy, look <a href="http://curl.haxx.se/download.html">here</a>.
