### ISSUE TITLE
Ignore unknown parms (e.g. querystrings)

### ISSUE THREAD

**Issue by ScottConroy** [marklogic-community/Corona#67]
Probably makes sense to ignore any request parameters passed into the system.  Right now requests with unknown parameters fail with an ENDPOINT NOT FOUND.  This seems to violates the robustness principle.  I think more importantly, additional parameters will make for useful extensibility options.

**Comment by eedeebee** [comment]
Full agreement here.

**Comment by hunterhacker** [comment]
Yeah, assuming the REST framework makes this easy to do, it's probably the best design.

**Comment by eedeebee** [comment]
If it doesn't, then it's a problem for the REST framework imo (and we should fix it).
