### ISSUE TITLE
RFE: Give custom query the true-query and false-query equivalents

### ISSUE THREAD

**Issue by hunterhacker** [marklogic-community/Corona#7]
Using cts:query people sometimes write cts:and-query(()) to indicate the equivalent of the non-existent cts:true-query() and cts:or-query(()) for the non-existent cts:false-query().  I think Corona should provide the true/false query primitives so this is more approachable to people.

**Comment by ryangrimm** [comment]
Added this in as: {"boolean": true} or {"boolean": false}.
